# Limpieza de datos

Seaborn parece ser una herramienta para utilizar varios datasets.

In [1]:
import pandas as pd
import seaborn as sns

Como se puede ver aquí, establecemos un dataframe llamando un dataset de Seaborn. En este caso estamos llamando al dataset "titanic".

In [2]:
# Cargar el dataset
df = sns.load_dataset("titanic")

# Verificar que cargó.
df.head() # o... df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

Ahora, queremos ver cómo está estructurada el dataset, y ver los tipos de datos de cada columna.

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

De un dataset limpio se espera que la cuenta de datos no nulos sea el mismo para todas las columnas, pero vemos que esto no se cumple:

Las columnas `age`, `embarked`, `embark_town` y `deck` no tienen la misma cantidad que el resto... hay que limpiar el dataframe.

Otro análisis del dataframe, más estadístico, se realiza con el método `describe()`.

In [4]:
df.describe(include='all')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
count,891.000000,891.000000,891,714.000000,891.000000,891.000000,891.000000,889,891,891,891,203,889,891,891
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,3,3,3,2,7,3,2,2
top,NaN,NaN,male,NaN,NaN,NaN,NaN,S,Third,man,True,C,Southampton,no,True
freq,NaN,NaN,577,NaN,NaN,NaN,NaN,644,491,537,537,59,644,549,537
mean,0.383838,2.308642,NaN,29.699118,0.523008,0.381594,32.204208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.486592,0.836071,NaN,14.526497,1.102743,0.806057,49.693429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,1.000000,NaN,0.420000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,0.000000,2.000000,NaN,20.125000,0.000000,0.000000,7.910400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,0.000000,3.000000,NaN,28.000000,0.000000,0.000000,14.454200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.000000,3.000000,NaN,38.000000,1.000000,0.000000,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.000000,3.000000,NaN,80.000000,8.000000,6.000000,512.329200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Primero, podemos ver que a la columna `age` se le realizó un análisis estadístico, esto se realizó sobre los datos que no son nulos. La media es de $29.7$ aproximadamente; y hay una desviación estándar algo alta, de $14.5$. Esto es porque también se puede ver los valores máximos y mínimos, que se alejan bastante de la media.

Por otro lado, la columna `sex` es una columna categórica, por lo que no hay un análisis numérico de esta columna. Sin embargo, hay una cuenta de cuántas categorías hay, la moda y la frecuencia de la moda.

Hay que tener cuidado de ver que los valores enteros son tratados como números reales.

In [5]:
df.isnull()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
887,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False
889,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False

Una cosa que hay que mencionar es que hay `None` y `NaN` no son los mismo; pues si bien `NaN` es considerado un valor numérico, `None` es un valor nulo o vacío.

Los motores de bases de datos no saben qué es `NaN`, así que hay que tener cuidado.

In [6]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

Otro tipo de análisis que se puede hacer es el de observar si hay registros duplicados o no; que es otro problema de los datasets.

In [7]:
df.duplicated().sum()

np.int64(107)

Entonces, de momento sabemos que hay columnas que poseen valores nulos y, para variar, el dataset tiene 107 registros duplicados. Divertido.

In [8]:
df[df.duplicated()]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
47,1,3,female,NaN,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True
76,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
77,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
87,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
95,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
870,0,3,male,26.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
877,0,3,male,19.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
878,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True

¿Qué podemos hacer con los datos nulos? Podemos eliminar el registro dependiendo del objetivo; pero en este caso vamos a reparar los datos sucios. Hay varios métodos que se pueden realizar para limpiar los datos y estos, nuevamente, dependen del objetivo.

Idealmente, hay que recuperar la información; rellenar con información que no altere mucho el significado del dataframe. Actualmente, para no afecta a la desviación estándar, los valores de edad nulos son rellenados con la edad promedio.

In [9]:
df['age'] = df['age'].fillna(df['age'].mean())

df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   13.002015    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   22.000000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   29.699118    0.000000    0.000000   14.454200
75%      1.000000    3.000000   35.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

Otro método es sacar el promedio de los cuartiles, y a cada cuartil rellenar con esa media.

In [10]:
df.groupby('pclass')['age'].mean().transform(lambda x: x.fillna(x.mean()))

df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   13.002015    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   22.000000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   29.699118    0.000000    0.000000   14.454200
75%      1.000000    3.000000   35.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

Una cosa que también se puede arreglar, que ya no es depuración de los datos, sino que normalización, es utilizar un valor equivalente para estandarizar el detalle de que la columna `sex` utiliza "male" y "female" para los datos.

In [11]:
df['sex'] = df['sex'].replace({"male": "M", "female": "F"})

df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,M,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,F,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,F,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,F,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,M,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,M,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,F,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,F,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,M,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,M,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

El caso de las columnas `deck` y `embark_town` es que no podemos conocer cuál era el valor que representan ahora los valores nulos. Una opción, dependiendo del tipo de análisis, es simplemente prescindir de la columna.

In [ ]:
df.drop(columns=["deck", "embark_town"], inplace = True)

# misma situacion con la columna embarked
df.drop(columns=["embarked"], inplace=True)

In [15]:
df

,survived,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,alive,alone
0,0,3,M,22.000000,1,0,7.2500,Third,man,True,no,False
1,1,1,F,38.000000,1,0,71.2833,First,woman,False,yes,False
2,1,3,F,26.000000,0,0,7.9250,Third,woman,False,yes,True
3,1,1,F,35.000000,1,0,53.1000,First,woman,False,yes,False
4,0,3,M,35.000000,0,0,8.0500,Third,man,True,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,M,27.000000,0,0,13.0000,Second,man,True,no,True
887,1,1,F,19.000000,0,0,30.0000,First,woman,False,yes,True
888,0,3,F,29.699118,1,2,23.4500,Third,woman,False,no,False
889,1,1,M,26.000000,0,0,30.0000,First,man,True,yes,True
890,0,3,M,32.000000,0,0,7.7500,Third,man,True,no,True

Podemos ver una última cosa, y es ver que la columna de `alive` es de tipo objeto, a pesar de que parece ser que quiere ser un valor booleano. Lo mejor es estandarizarlo.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   survived    891 non-null    int64
 1   pclass      891 non-null    int64
 2   sex         891 non-null    object
 3   age         891 non-null    float64
 4   sibsp       891 non-null    int64
 5   parch       891 non-null    int64
 6   fare        891 non-null    float64
 7   class       891 non-null    category
 8   who         891 non-null    object
 9   adult_male  891 non-null    bool
 10  alive       891 non-null    object
 11  alone       891 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), object(3)
memory usage: 65.5+ KB

In [19]:
df['alive'].unique()

array(['no', 'yes'], dtype=object)

In [22]:
df['alive'] = df['alive'].replace({"no": False, "yes": True})

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   survived    891 non-null    int64
 1   pclass      891 non-null    int64
 2   sex         891 non-null    object
 3   age         891 non-null    float64
 4   sibsp       891 non-null    int64
 5   parch       891 non-null    int64
 6   fare        891 non-null    float64
 7   class       891 non-null    category
 8   who         891 non-null    object
 9   adult_male  891 non-null    bool
 10  alive       891 non-null    bool
 11  alone       891 non-null    bool
dtypes: bool(3), category(1), float64(2), int64(4), object(2)
memory usage: 59.4+ KB

Viendo el dataframe, a primera vista, vemos que las columnas `sex`, `who` y `adult_male` parecen ser que tratan de decir lo mismo; pero antes de deshacerse de las columnas, podemos observar mejor estas columnas.

In [ ]:
df[['sex', 'who', 'adult_male']].drop_duplicates()

  sex    who  adult_male
0   M    man        True
1   F  woman       False
7   M  child       False
9   F  child       False

In [26]:
df['who'].unique()

array(['man', 'woman', 'child'], dtype=object)

Así, se puede ver que las columnas cumplen con una función que no es duplicada. Ahora, viendo que hay niños; hay un problema, y es que la edad que fue llenada en los datos nulos no es correcto, pues estamos asignando edades de 20 años a registros catalogados como niños.