In [1]:
import pandas as pd

clientes = pd.DataFrame({
    "id_cliente": [1, 2, 3, 5],
    "nombre": ["Ana", "Luis", "Carlos", "Marta"],
    "departamento": ["SS", "SM", "CH", "SS"]
})

ventas = pd.DataFrame({
    "id_cliente": [1, 2, 3, 4],
    "producto": ["A", "B", "C", "D"],
    "cantidad": [10, 29, 8, 92]
})

In [2]:
clientes.head(), ventas.head()

(   id_cliente  nombre departamento
 0           1     Ana           SS
 1           2    Luis           SM
 2           3  Carlos           CH
 3           5   Marta           SS,
    id_cliente producto  cantidad
 0           1        A        10
 1           2        B        29
 2           3        C         8
 3           4        D        92)

In [ ]:
# this is an inner join, basically
join_clientes_ventas = pd.merge(clientes, ventas, on="id_cliente", how="inner")
join_clientes_ventas

   id_cliente  nombre departamento producto  cantidad
0           1     Ana           SS        A        10
1           2    Luis           SM        B        29
2           3  Carlos           CH        C         8

In [ ]:
# this is a left join, where clientes is shown completely
# but is there is not a register on the other dataframe, its filled with NaN's
pd.merge(clientes, ventas, on="id_cliente", how="left")

   id_cliente  nombre departamento producto  cantidad
0           1     Ana           SS        A      10.0
1           2    Luis           SM        B      29.0
2           3  Carlos           CH        C       8.0
3           5   Marta           SS      NaN       NaN

In [7]:
# same with this one, a right join
pd.merge(clientes, ventas, on="id_cliente", how="right")

   id_cliente  nombre departamento producto  cantidad
0           1     Ana           SS        A        10
1           2    Luis           SM        B        29
2           3  Carlos           CH        C         8
3           4     NaN          NaN        D        92

In [8]:
# oh, yeah, and there are outer joins
pd.merge(clientes, ventas, on="id_cliente", how="outer")

   id_cliente  nombre departamento producto  cantidad
0           1     Ana           SS        A      10.0
1           2    Luis           SM        B      29.0
2           3  Carlos           CH        C       8.0
3           4     NaN          NaN        D      92.0
4           5   Marta           SS      NaN       NaN

In [10]:
# retomando que: join_clientes_ventas = pd.merge(clientes, ventas, on="id_cliente", how="inner")
join_clientes_ventas[["nombre","producto"]]

   nombre producto
0     Ana        A
1    Luis        B
2  Carlos        C

Para mayor rigidez, es posible trabajar con una forma más parecida a la forma de las bases de datos, usando los parámetros `left_on`, `right_on`; para establecer la llave de una tabla y de la otra.

In [12]:
pd.merge(clientes, ventas, left_on="id_cliente", right_on="id_cliente", how="inner")

   id_cliente  nombre departamento producto  cantidad
0           1     Ana           SS        A        10
1           2    Luis           SM        B        29
2           3  Carlos           CH        C         8

In [17]:
df_left = pd.merge(clientes, ventas, left_on="id_cliente", right_on="id_cliente", how="left")
df_left.dropna()

   id_cliente  nombre departamento producto  cantidad
0           1     Ana           SS        A      10.0
1           2    Luis           SM        B      29.0
2           3  Carlos           CH        C       8.0